#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const version = "0.17.0";
const tarballUrl = "https://registry.npmjs.org/katex/-/katex-0.17.0.tgz";
const integrity = "sha512-Vdw0ATsQ9V+LuegM/BTwQqV/6cTl5lbGcIrU+BCgLxyf6bo38ybOr372tuSIxir3CN720flu1meYR6XzNMwQnw==";
const root = fileURLToPath(new URL("..", import.meta.url));
const vendorDir = join(root, "src", "vendor");
const outputPath = join(vendorDir, "katex.ts");
const licensePath = join(vendorDir, "katex-license.txt");

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});

async function main() {
  const tempDir = mkdtempSync(join(tmpdir(), "quizmcp-katex-"));
  try {
    const tarballPath = join(tempDir, `katex-${version}.tgz`);
    const response = await fetch(tarballUrl);
    if (!response.ok) {
      throw new Error(`Failed to download KaTeX ${version}: HTTP ${response.status}`);
    }

    const tarball = Buffer.from(await response.arrayBuffer());
    verifyIntegrity(tarball);
    writeFileSync(tarballPath, tarball);

    const extractDir = join(tempDir, "extract");
    mkdirSync(extractDir);
    run("tar", ["-xzf", tarballPath, "-C", extractDir]);

    const packageDir = join(extractDir, "package");
    const minifiedJsPath = join(packageDir, "dist", "katex.min.js");
    if (!existsSync(minifiedJsPath)) {
      throw new Error("Downloaded KaTeX package did not contain dist/katex.min.js.");
    }

    const minifiedJs = readFileSync(minifiedJsPath, "utf8");
    const license = readFileSync(join(packageDir, "LICENSE"), "utf8");
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, renderModule(minifiedJs), "utf8");
    writeFileSync(licensePath, license, "utf8");
    console.log(`Vendored KaTeX ${version} into ${outputPath}`);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function verifyIntegrity(buffer) {
  const [algorithm, expected] = integrity.split("-", 2);
  if (algorithm !== "sha512" || !expected) {
    throw new Error("Unsupported KaTeX integrity format.");
  }

  const actual = createHash("sha512").update(buffer).digest("base64");
  if (actual !== expected) {
    throw new Error("Downloaded KaTeX tarball did not match pinned integrity.");
  }
}

function renderModule(minifiedJs) {
  return [
    "// Generated by scripts/vendor-katex.mjs. Do not edit by hand.",
    `export const KATEX_VERSION = ${JSON.stringify(version)};`,
    `export const KATEX_JS = ${JSON.stringify(minifiedJs)};`,
    ""
  ].join("\n");
}

function run(command, args) {
  const result = spawnSync(command, args, { encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed: ${result.stderr || result.stdout}`);
  }
}
